{% set name = "ytmusicapi" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ytmusicapi-{{ version }}.tar.gz
  sha256: 454facdf5907c32b77cb035f54c76d5a9d3fb0316933b1a1cecd06110ff85ecf

build:
  entry_points:
    - ytmusicapi = ytmusicapi.setup:main
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=65
    - setuptools-scm >=7
    - requests
    - pip
  run:
    - python >=3.8
    - requests >=2.22

test:
  imports:
    - ytmusicapi
  commands:
    - pip check
    - ytmusicapi --help
  requires:
    - pip

about:
  home: https://github.com/sigma67/ytmusicapi
  dev_url: https://github.com/sigma67/ytmusicapi
  summary: Unofficial API for YouTube Music
  license: MIT
  license_file: LICENSE
  doc_url: https://ytmusicapi.readthedocs.io/
  description: ytmusicapi is a Python 3 library to send requests to the YouTube Music API. It emulates YouTube Music web client requests using the user's cookie data for authentication.

extra:
  recipe-maintainers:
    - HeavyTony2
