{% set name = "ytmusicapi" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ytmusicapi-{{ version }}.tar.gz
  sha256: fea7c502482597e8f50d484bf5d455bd17403c8fa93ff94ebe1f93da816ff394

build:
  entry_points:
    - ytmusicapi = ytmusicapi.setup:main
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=7
    - requests
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.22

test:
  imports:
    - ytmusicapi
  commands:
    - pip check
    - ytmusicapi --help
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/sigma67/ytmusicapi
  dev_url: https://github.com/sigma67/ytmusicapi
  summary: Unofficial API for YouTube Music
  license: MIT
  license_file: LICENSE
  doc_url: https://ytmusicapi.readthedocs.io/
  description: |
    ytmusicapi is a Python 3 library to send requests to the YouTube Music API. It emulates YouTube Music web client requests using the user's cookie data for authentication.

extra:
  recipe-maintainers:
    - HeavyTony2
